<?php
return [
    'app' => [
        'name' => 'ANEO Gestão',
        'base_url' => '',
        'public_url' => '',   // URL pública do sistema, ex: https://erp-hml.aneobrasil.com.br — configure em config.local.php
        'timezone' => 'America/Sao_Paulo',
        'default_pagination' => 50,
        'pagination_options' => [50, 100, 200],
        'uploads_dir' => __DIR__ . '/uploads',
    ],
    'db' => [
        'host' => 'localhost',
        'port' => 3306,
        'name' => 'aneo_gestao',
        'user' => 'root',
        'pass' => '',
        'charset' => 'utf8mb4',
    ],
    'zoom' => [
        'enabled' => false,
        'provider' => 'manual',
        'client_id' => '',
        'client_secret' => '',
        'account_id' => '',
    ],
    'whatsapp' => [
        'default_country_code' => '55',
    ],
    'fiscal' => [
        'enabled' => false,
        'provider' => 'manual',
        'environment' => 'sandbox',
        'base_url' => '',
        'api_token' => '',
        'company_document' => '',
        'company_name' => '',
    ],
    'bank_slip' => [
        'enabled' => false,
        'provider' => 'manual',
        'environment' => 'sandbox',
        'base_url' => '',
        'api_token' => '',
        'webhook_secret' => '',
        'wallet' => '',
        'beneficiary_document' => '',
        'beneficiary_name' => '',
    ],
    'admin_ai' => [
        'enabled' => true,
        'provider' => 'openrouter',
        'base_url' => 'https://openrouter.ai/api/v1',
        'api_key' => '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',
        'model' => 'google/gemma-3-12b-it:free',
        'temperature' => 0.2,
        'max_tokens' => 1000,
        'timeout_seconds' => 60,
        'history_messages' => 6,
        'http_referer' => 'http://localhost/aneo',
        'app_title' => 'ANEO Gestao',
        'system_prompt' => '',
    ],
    'chatwoot' => [
        'enabled' => true,
        'base_url' => 'https://app.chatwoot.com',
        'account_id' => '154715',
        'inbox_id' => '98949',
        'api_access_token' => 'bQ9iwKXWzTQRkCKzskzfZqyu',
        'webhook_token' => 'trocar_token_webhook',
        'bot_enabled' => true,
        'bot_start_keywords' => ['oi', 'ola', 'olaa', 'bom dia', 'boa tarde', 'boa noite'],
        'bot_message_menu' => "Ola! Eu sou a Bia.\nPara te ajudar melhor, como voce se chama?\nE voce ja e nosso aluno ou tem interesse em conhecer nossos cursos?\n\n1 - Sim, sou aluno\n2 - Nao, tenho interesse nos cursos",
        'bot_message_name_city' => "Para te ajudar melhor, qual e o seu nome?\nE em qual cidade voce tem interesse em cursar?",
        'bot_message_invalid_option' => "Para continuarmos, responda com 1 (sou aluno) ou 2 (tenho interesse).",
        'bot_message_city_retry' => "Perfeito. Me informe sua cidade de interesse para eu te direcionar ao especialista correto.",
        'bot_message_handoff' => "Para te ajudar corretamente, vou encaminhar seu atendimento para o especialista da unidade {{cidade}}. Aguarde um momento por favor.",
        'bot_city_team_map' => [
            'barueri' => null,
            'sao paulo' => null,
            'osasco' => null,
        ],
    ],
    'd4sign' => [
        'enabled' => true,
        'base_url' => 'https://sandbox.d4sign.com.br',
        'token_api' => 'live_a6aea6989d3a559a7d6b25009964b65d9eb11a0a5efeef75556b8a779ed4c430',
        'crypt_key' => 'live_crypt_Qis61YCAMyhWV3uamY1zX3fWIiY9BYaF',
        'safe_uuid' => 'bd73a0a8-699e-4141-8ad3-6386ed51d75f',
        'webhook_token' => 'trocar_token_d4sign',
        'webhook_hmac_secret' => '',
    ],
    'automation' => [
        'enabled' => true,
        'enrollment_webhook_token' => 'e9da9a6c717449839848e582ed22d7fdb97e6e3dcf084610b3e22030719c3e6b',
        'finance_webhook_token' => 'b47c51f972f5ef1303c52cd6586f0dd5c865ec76b122d307b76bb980f452a314',
        'finance_reminder_days_before' => 3,
        'finance_admin_email' => 'vinicius14c@hotmail.com',
        'finance_bcc_email' => 'financeiro@aneobrasil.com.br',
        'payment_approved_statuses' => ['confirmed', 'received', 'paid'],
        'contract_signed_statuses' => ['signed', 'completed', 'concluded', 'done'],
    ],
    'cron' => [
        'enabled' => true,
        'secret_token' => 'aneo_cron_' . '2026_troque_este_token',   // altere no config.local.php
    ],
    'support' => [
        'notification_email' => 'vinicius14c@hotmail.com',
        'from_email' => 'nao-responda@aneo.local',
        'external_webhook_enabled' => false,
        'external_webhook_url' => '',
        'external_webhook_token' => 'trocar_token_chamados',
        'webhook_company_id' => 1,
    ],
    'smtp' => [
        'enabled' => false,
        'host' => '',
        'port' => 587,
        'security' => 'tls',
        'username' => '',
        'password' => '',
        'from_email' => 'nao-responda@aneo.local',
        'from_name' => 'ANEO Gestao',
        'reply_to' => '',
        'timeout' => 20,
    ],
    'support_desk' => [
        'enabled' => true,
        'required_permissions' => ['support.desk', 'requests.manage'],
    ],
    'roles' => [
        'admin' => [
            'label' => 'Administrador',
            'permissions' => ['*'],
        ],
        'suporte' => [
            'label' => 'Suporte',
            'permissions' => ['dashboard', 'help'],
        ],
        'professor' => [
            'label' => 'Professor',
            'permissions' => [
                'students',
                'students.create',
                'students.edit',
                'courses',
                'courses.create',
                'courses.edit',
                'courses.category',
                'courses.enrollment',
                'courses.exam',
                'courses.comment',
            ],
        ],
    ],
    'permissions_catalog' => [
        'modules' => [
            'dashboard' => 'Dashboard',
            'gda' => 'Gestao do Aluno',
            'kanban' => 'Kanban Cliente',
            'students' => 'Alunos',
            'leads' => 'Leads',
            'finance' => 'Financeiro',
            'chatwoot' => 'Atendimento',
            'ai_chat' => 'Assistente IA',
            'signatures' => 'Assinaturas',
            'arsenal' => 'Arsenal Digital',
            'courses' => 'Cursos EAD',
            'projects' => 'Projetos',
            'tasks' => 'Tarefas',
            'requests' => 'Solicitações',
            'automations' => 'Automações',
            'help' => 'Chat IA Jully',
            'companies' => 'Empresas',
        ],
        'functions' => [
            'students.create' => 'Alunos: criar',
            'students.edit' => 'Alunos: editar/ativar/upload',
            'students.delete' => 'Alunos: excluir',
            'students.import' => 'Alunos: importar CSV',
            'students.export' => 'Alunos: exportar CSV',
            'students.bulk' => 'Alunos: acoes em massa',
            'leads.create' => 'Leads: criar',
            'leads.edit' => 'Leads: editar/interagir',
            'leads.delete' => 'Leads: excluir',
            'leads.status' => 'Leads: alterar status',
            'leads.bulk' => 'Leads: acoes em massa',
            'leads.convert' => 'Leads: converter em aluno',
            'leads.export' => 'Leads: exportar CSV',
            'leads.settings' => 'Leads: configurar pipeline',
            'kanban.move' => 'Kanban: mover cards',
            'kanban.settings' => 'Kanban: configurar status',
            'finance.invoice.create' => 'Financeiro: criar fatura',
            'finance.invoice.delete' => 'Financeiro: excluir fatura',
            'finance.invoice.settle' => 'Financeiro: baixa de contas a receber',
            'finance.invoice.nfe' => 'Financeiro: gerar nota fiscal',
            'finance.invoice.export' => 'Financeiro: exportar faturas',
            'finance.invoice.recurrence' => 'Financeiro: gerar recorrentes',
            'finance.invoice.whatsapp' => 'Financeiro: enviar boleto por WhatsApp',
            'finance.invoice.boleto.generate' => 'Financeiro: gerar boleto via API',
            'finance.invoice.boleto.sync' => 'Financeiro: sincronizar status do boleto',
            'finance.payment.create' => 'Financeiro: registrar pagamento',
            'finance.reports.export' => 'Financeiro: exportar relatorios',
            'chat.open' => 'Atendimento: abrir/iniciar conversa Chatwoot',
            'ai_chat.ask' => 'Assistente IA: consultar base interna',
            'students.whatsapp' => 'Alunos: conversar no WhatsApp',
            'signatures.create' => 'Assinaturas: criar contrato',
            'signatures.send' => 'Assinaturas: enviar para assinatura',
            'signatures.sync' => 'Assinaturas: sincronizar status',
            'signatures.delete' => 'Assinaturas: excluir solicitacao',
            'arsenal.manage' => 'Arsenal: gerenciar acervo e vinculos',
            'courses.create' => 'Cursos: criar',
            'courses.edit' => 'Cursos: editar',
            'courses.delete' => 'Cursos: excluir',
            'courses.category' => 'Cursos: gerenciar categorias',
            'courses.enrollment' => 'Cursos: gerenciar matriculas',
            'courses.exam' => 'Cursos: gerenciar exames',
            'courses.comment' => 'Cursos: gerenciar comentarios',
            'projects.manage' => 'Projetos: criar/editar/excluir',
            'tasks.manage' => 'Tarefas: criar/editar/excluir',
            'requests.manage' => 'Solicitações: criar/editar/excluir',
            'support.desk' => 'Central Tecnica: administrar chamados',
            'automations.manage' => 'Automações: criar/editar/excluir',
            'help.manage' => 'Chat IA Jully: criar/editar/excluir',
            'gda.move' => 'Gestao do Aluno: mover cards',
            'gda.notes' => 'Gestao do Aluno: notas e checklists',
            'gda.settings' => 'Gestao do Aluno: configuracoes',
        ],
    ],
    'student_flags' => [
        'Documentacao incompleta',
        'Contrato pendente',
        'Necessita contato',
    ],
];
