-- Aplicar: mysql -u <user> -p<pass> <db> < migrations/20260523_finance_payables.sql

CREATE TABLE IF NOT EXISTS suppliers (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_id INT UNSIGNED NOT NULL,
    name VARCHAR(160) NOT NULL,
    document VARCHAR(32) NULL,
    contact_name VARCHAR(120) NULL,
    email VARCHAR(180) NULL,
    phone VARCHAR(40) NULL,
    whatsapp VARCHAR(40) NULL,
    pix_key VARCHAR(160) NULL,
    bank_name VARCHAR(120) NULL,
    bank_agency VARCHAR(40) NULL,
    bank_account VARCHAR(60) NULL,
    notes TEXT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_suppliers_company_active (company_id, is_active),
    INDEX idx_suppliers_name (name),
    INDEX idx_suppliers_document (document),
    CONSTRAINT fk_suppliers_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_suppliers_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_suppliers_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS payables (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_id INT UNSIGNED NOT NULL,
    supplier_id INT UNSIGNED NOT NULL,
    payment_method_id INT UNSIGNED NULL,
    payable_number VARCHAR(60) NOT NULL,
    description VARCHAR(255) NOT NULL,
    category VARCHAR(120) NULL,
    competence_date DATE NULL,
    due_date DATE NOT NULL,
    amount DECIMAL(12,2) NOT NULL,
    paid_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    paid_at DATE NULL,
    status ENUM('draft', 'open', 'partial', 'paid', 'overdue', 'cancelled') NOT NULL DEFAULT 'open',
    notes TEXT NULL,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE KEY uk_payables_company_number (company_id, payable_number),
    INDEX idx_payables_company_due (company_id, due_date),
    INDEX idx_payables_company_status (company_id, status),
    INDEX idx_payables_supplier (supplier_id),
    INDEX idx_payables_payment_method (payment_method_id),
    CONSTRAINT fk_payables_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_payables_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_payables_payment_method FOREIGN KEY (payment_method_id) REFERENCES payment_methods(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_payables_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_payables_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS payable_payments (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_id INT UNSIGNED NOT NULL,
    payable_id INT UNSIGNED NOT NULL,
    payment_method_id INT UNSIGNED NULL,
    amount DECIMAL(12,2) NOT NULL,
    paid_at DATE NOT NULL,
    notes TEXT NULL,
    created_by INT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_payable_payments_company (company_id),
    INDEX idx_payable_payments_payable (payable_id),
    INDEX idx_payable_payments_method (payment_method_id),
    CONSTRAINT fk_payable_payments_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_payable_payments_payable FOREIGN KEY (payable_id) REFERENCES payables(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_payable_payments_method FOREIGN KEY (payment_method_id) REFERENCES payment_methods(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_payable_payments_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
