CREATE TABLE IF NOT EXISTS signature_requests (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    student_id INT UNSIGNED NOT NULL,
    title VARCHAR(180) NOT NULL,
    description TEXT NULL,
    signer_name VARCHAR(180) NOT NULL,
    signer_email VARCHAR(180) NOT NULL,
    signer_phone VARCHAR(40) NULL,
    file_original_path VARCHAR(255) NOT NULL,
    file_signed_path VARCHAR(255) NULL,
    d4sign_safe_uuid VARCHAR(120) NULL,
    d4sign_document_uuid VARCHAR(120) NULL,
    d4sign_signer_key VARCHAR(255) NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'draft',
    d4sign_status VARCHAR(80) NULL,
    sent_at DATETIME NULL,
    signed_at DATETIME NULL,
    last_synced_at DATETIME NULL,
    last_error TEXT NULL,
    metadata_json LONGTEXT NULL,
    created_by INT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_signature_requests_student (student_id),
    INDEX idx_signature_requests_status (status),
    UNIQUE KEY uk_signature_requests_document (d4sign_document_uuid),
    CONSTRAINT fk_signature_requests_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_signature_requests_user FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS signature_events (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    signature_request_id INT UNSIGNED NULL,
    d4sign_document_uuid VARCHAR(120) NULL,
    event_type VARCHAR(80) NULL,
    event_status VARCHAR(80) NULL,
    event_message VARCHAR(255) NULL,
    payload_json LONGTEXT NULL,
    received_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL,
    INDEX idx_signature_events_request (signature_request_id),
    INDEX idx_signature_events_document (d4sign_document_uuid),
    CONSTRAINT fk_signature_events_request FOREIGN KEY (signature_request_id) REFERENCES signature_requests(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
